name: Build / Deploy to PyPi
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      run: echo "Running unit tests"
      run: tox -e unit
  # build:
  #   runs-on: ubuntu-latest
