name: Code Validation
on:
  pull_request:
    branches: [ master ]
jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: | 
        pip install pip --upgrade
        pip install tox tox-gh-actions
  
    - name: lint
      run: | 
        tox -e lint
    
  unit-tests:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: | 
        pip install pip --upgrade
        pip install tox tox-gh-actions

    - name: unit tests
      with:
        OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }} 
      run: | 
        env
        tox -e unit

  # build:
  #   runs-on: ubuntu-latest
